import { MovieType } from './types';

// Array principal de películas con información completa
const movies: MovieType[] = [
  {
    id: 1,
    title: 'Dune: Parte Dos',
    anio: 2024,
    genero: 'Ciencia ficción',
    rating: 8.2,
    duracion: '2h 46m',
    youtube_id: 'U2Qp5pL3ovA',
    trailer_url: 'https://www.youtube.com/watch?v=U2Qp5pL3ovA',
    miniatura: 'https://i.ytimg.com/vi/U2Qp5pL3ovA/mqdefault.jpg',
    descripcion:
      'Paul Atreides se une a los Fremen en un camino de guerra y venganza mientras enfrenta elecciones que afectarán el destino del universo.',
    categoria: 'estrenos',
  },
  {
    id: 2,
    title: 'Venom: The Last Dance',
    anio: 2024,
    genero: 'Acción',
    rating: 6.1,
    duracion: '1h 50m',
    youtube_id: 'a4wqO-9vKk8',
    trailer_url: 'https://www.youtube.com/watch?v=a4wqO-9vKk8',
    miniatura: 'https://i.ytimg.com/vi/a4wqO-9vKk8/mqdefault.jpg',
    descripcion:
      'Eddie Brock y Venom deben tomar una decisión devastadora mientras son perseguidos por un misterioso militar y monstruos alienígenas.',
    categoria: 'estrenos',
  },
  {
    id: 3,
    title: 'Deadpool & Wolverine',
    anio: 2024,
    genero: 'Acción',
    rating: 8.1,
    duracion: '2h 15m',
    youtube_id: '73_1biulk2k',
    trailer_url: 'https://www.youtube.com/watch?v=73_1biulk2k',
    miniatura: 'https://i.ytimg.com/vi/73_1biulk2k/mqdefault.jpg',
    descripcion:
      'Deadpool y Wolverine se unen en una aventura llena de acción y humor característico de Deadpool.',
    categoria: 'estrenos',
  },
  {
    id: 4,
    title: 'Joker: Folie à Deux',
    anio: 2024,
    genero: 'Drama',
    rating: 7.9,
    duracion: '2h 30m',
    youtube_id: 'xy6d5aIDo8s',
    trailer_url: 'https://www.youtube.com/watch?v=xy6d5aIDo8s',
    miniatura: 'https://i.ytimg.com/vi/xy6d5aIDo8s/mqdefault.jpg',
    descripcion:
      'Secuela del éxito Joker, explorando la relación con Harley Quinn en un musical psicológico perturbador.',
    categoria: 'estrenos',
  },
  {
    id: 5,
    title: 'Inside Out 2',
    anio: 2024,
    genero: 'Animación',
    rating: 8.0,
    duracion: '1h 45m',
    youtube_id: 'P2Fkj_s9A8o',
    trailer_url: 'https://www.youtube.com/watch?v=P2Fkj_s9A8o',
    miniatura: 'https://i.ytimg.com/vi/P2Fkj_s9A8o/mqdefault.jpg',
    descripcion: 'Nuevas emociones llegan a la mente de Riley mientras atraviesa la adolescencia.',
    categoria: 'estrenos',
  },
  {
    id: 6,
    title: 'Kingdom of the Planet of the Apes',
    anio: 2024,
    genero: 'Ciencia ficción',
    rating: 7.5,
    duracion: '2h 25m',
    youtube_id: 'N6OgcFQb6vI',
    trailer_url: 'https://www.youtube.com/watch?v=N6OgcFQb6vI',
    miniatura: 'https://i.ytimg.com/vi/N6OgcFQb6vI/mqdefault.jpg',
    descripcion:
      'Nueva entrega de la saga donde los simios dominan la Tierra y enfrentan nuevos desafíos.',
    categoria: 'estrenos',
  },
  {
    id: 7,
    title: 'Godzilla x Kong: The New Empire',
    anio: 2024,
    genero: 'Acción',
    rating: 6.8,
    duracion: '2h 05m',
    youtube_id: 'qqrpMRoPk7w',
    trailer_url: 'https://www.youtube.com/watch?v=qqrpMRoPk7w',
    miniatura: 'https://i.ytimg.com/vi/qqrpMRoPk7w/mqdefault.jpg',
    descripcion:
      'Godzilla y Kong se unen para enfrentar una amenaza que pone en peligro la existencia de ambos reinos.',
    categoria: 'estrenos',
  },
  {
    id: 8,
    title: 'Furiosa: A Mad Max Saga',
    anio: 2024,
    genero: 'Acción',
    rating: 8.3,
    duracion: '2h 28m',
    youtube_id: 'XJMuhwVlca4',
    trailer_url: 'https://www.youtube.com/watch?v=XJMuhwVlca4',
    miniatura: 'https://i.ytimg.com/vi/XJMuhwVlca4/mqdefault.jpg',
    descripcion:
      'Origen de Furiosa, personaje de Mad Max: Fury Road, en una historia de venganza y supervivencia.',
    categoria: 'estrenos',
  },
  {
    id: 9,
    title: 'The Batman - Part II',
    anio: 2025,
    genero: 'Acción',
    rating: 0.5,
    duracion: '1h 50m',
    youtube_id: 'yKcbzLiKZbs',
    trailer_url: 'https://www.youtube.com/watch?v=yKcbzLiKZbs',
    miniatura: 'https://i.ytimg.com/vi/yKcbzLiKZbs/mqdefault.jpg',
    descripcion:
      'Secuela de The Batman (2022) con Robert Pattinson, explorando nuevos villanos y desafíos para el héroe.',
    categoria: 'proximamente',
  },
  {
    id: 10,
    title: 'Gladiator II',
    anio: 2024,
    genero: 'Acción',
    rating: 0.9,
    duracion: '2h 50m',
    youtube_id: 'pw7k-YxZtEA',
    trailer_url: 'https://www.youtube.com/watch?v=pw7k-YxZtEA',
    miniatura: 'https://i.ytimg.com/vi/pw7k-YxZtEA/mqdefault.jpg',
    descripcion:
      'Secuela del clásico Gladiador, continuando la historia en la antigua Roma con nuevos personajes.',
    categoria: 'proximamente',
  },
  {
    id: 11,
    title: 'Avengers: Endgame',
    anio: 2019,
    genero: 'Acción',
    rating: 8.4,
    duracion: '3h 01m',
    youtube_id: 'TcMBFSGVi1c',
    trailer_url: 'https://www.youtube.com/watch?v=TcMBFSGVi1c',
    miniatura: 'https://i.ytimg.com/vi/TcMBFSGVi1c/mqdefault.jpg',
    descripcion:
      'Los Vengadores se reúnen para revertir el Snap de Thanos en la conclusión épica de la Infinity Saga.',
    categoria: 'clasicos',
  },
  {
    id: 12,
    title: 'The Dark Knight',
    anio: 2008,
    genero: 'Acción',
    rating: 9.0,
    duracion: '2h 32m',
    youtube_id: 'EXeTwQWrcwY',
    trailer_url: 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
    miniatura: 'https://i.ytimg.com/vi/EXeTwQWrcwY/mqdefault.jpg',
    descripcion: 'Batman enfrenta al Joker en una batalla por el alma de Gotham City.',
    categoria: 'clasicos',
  },
  {
    id: 13,
    title: 'Inception',
    anio: 2010,
    genero: 'Ciencia ficción',
    rating: 8.8,
    duracion: '2h 28m',
    youtube_id: 'YoHD9XEInc0',
    trailer_url: 'https://www.youtube.com/watch?v=YoHD9XEInc0',
    miniatura: 'https://i.ytimg.com/vi/YoHD9XEInc0/mqdefault.jpg',
    descripcion:
      'Un ladrón que roba secretos through dream-sharing technology tiene una última oportunidad de redención.',
    categoria: 'clasicos',
  },
  {
    id: 14,
    title: 'The Shawshank Redemption',
    anio: 1994,
    genero: 'Drama',
    rating: 9.3,
    duracion: '2h 22m',
    youtube_id: '6hB3S9bIaco',
    trailer_url: 'https://www.youtube.com/watch?v=6hB3S9bIaco',
    miniatura: 'https://i.ytimg.com/vi/6hB3S9bIaco/mqdefault.jpg',
    descripcion:
      'La historia de amistad y esperanza de dos prisioneros en la prisión de Shawshank.',
    categoria: 'clasicos',
  },
  {
    id: 15,
    title: 'Pulp Fiction',
    anio: 1994,
    genero: 'Crimen',
    rating: 8.9,
    duracion: '2h 34m',
    youtube_id: 's7EdQ4FqbhY',
    trailer_url: 'https://www.youtube.com/watch?v=s7EdQ4FqbhY',
    miniatura: 'https://i.ytimg.com/vi/s7EdQ4FqbhY/mqdefault.jpg',
    descripcion:
      'Historias interconectadas de criminales en Los Ángeles, dirigida por Quentin Tarantino.',
    categoria: 'clasicos',
  },
];

const moviesSalientNew: MovieType[] = movies.slice(0, 5);

const moviesSalientWeek: MovieType[] = movies.slice(5, 10);

const moviesSalientCoomingSoon: MovieType[] = movies.slice(10, 15);

export { movies, moviesSalientNew, moviesSalientWeek, moviesSalientCoomingSoon };
